export const ONE_SEC_IN_MILLISECONDS = 1000
export const ONE_MINUTE_IN_SECONDS = 60
export const ONE_HOUR_IN_SECONDS = ONE_MINUTE_IN_SECONDS * 60
export const ONE_DAY_IN_SECONDS = ONE_HOUR_IN_SECONDS * 24
export const ONE_WEEK_IN_SECONDS = ONE_DAY_IN_SECONDS * 7
export const ONE_MONTH_IN_SECONDS = ONE_DAY_IN_SECONDS * 30
export const ONE_YEAR_IN_SECONDS = ONE_DAY_IN_SECONDS * 365

export const INTERVAL_TIME_IN_MILLISECONDS =
  ONE_SEC_IN_MILLISECONDS * ONE_MINUTE_IN_SECONDS * 5
