import { StBTC as StBTCTypechain } from "@acre-btc/contracts/typechain/contracts/StBTC"
import stBTC from "@acre-btc/contracts/deployments/sepolia/stBTC.json"

import {
  EthersContractConfig,
  EthersContractDeployment,
  EthersContractWrapper,
} from "./contract"
import { ChainIdentifier, StBTC } from "../contracts"
import { EthereumNetwork } from "./network"
import { Hex } from "../utils"

class EthereumStBTC
  // @ts-expect-error TODO: Figure out why type generated by typechain does not
  // satisfy the constraint `Contract`. Error: `Property '[internal]' is missing
  // in type 'StBTC' but required in type 'BaseContract'`.
  extends EthersContractWrapper<StBTCTypechain>
  implements StBTC
{
  readonly #BASIS_POINT_SCALE = BigInt(1e4)

  #cache: {
    entryFeeBasisPoints?: bigint
  } = { entryFeeBasisPoints: undefined }

  constructor(config: EthersContractConfig, network: EthereumNetwork) {
    let artifact: EthersContractDeployment

    switch (network) {
      case "sepolia":
        artifact = stBTC
        break
      case "mainnet":
      default:
        throw new Error("Unsupported network")
    }

    super(config, artifact)
  }

  getChainIdentifier(): ChainIdentifier {
    return this.getAddress()
  }

  /**
   * @see {StBTC#totalAssets}
   */
  totalAssets(): Promise<bigint> {
    return this.instance.totalAssets()
  }

  /**
   * @see {StBTC#balanceOf}
   */
  balanceOf(identifier: ChainIdentifier): Promise<bigint> {
    return this.instance.balanceOf(`0x${identifier.identifierHex}`)
  }

  /**
   * @see {StBTC#assetsBalanceOf}
   */
  assetsBalanceOf(identifier: ChainIdentifier): Promise<bigint> {
    return this.instance.assetsBalanceOf(`0x${identifier.identifierHex}`)
  }

  /**
   * @see {StBTC#calculateDepositFee}
   */
  async calculateDepositFee(amount: bigint): Promise<bigint> {
    const entryFeeBasisPoints = await this.#getEntryFeeBasisPoints()

    return (
      (amount * entryFeeBasisPoints) /
      (entryFeeBasisPoints + this.#BASIS_POINT_SCALE)
    )
  }

  async #getEntryFeeBasisPoints(): Promise<bigint> {
    if (this.#cache.entryFeeBasisPoints) {
      return this.#cache.entryFeeBasisPoints
    }

    this.#cache.entryFeeBasisPoints = await this.instance.entryFeeBasisPoints()

    return this.#cache.entryFeeBasisPoints
  }

  encodeApproveAndCallFunctionData(
    spender: ChainIdentifier,
    amount: bigint,
    extraData: Hex,
  ): Hex {
    const data = this.instance.interface.encodeFunctionData("approveAndCall", [
      `0x${spender.identifierHex}`,
      amount,
      extraData.toPrefixedString(),
    ])

    return Hex.from(data)
  }
}

// eslint-disable-next-line import/prefer-default-export
export { EthereumStBTC }
