import { StBTC as StBTCTypechain } from "core/typechain/contracts/StBTC"
import stBTC from "./artifacts/sepolia/stBTC.json"
import {
  EthersContractConfig,
  EthersContractDeployment,
  EthersContractWrapper,
} from "./contract"
import { ChainIdentifier, StBTC } from "../contracts"
import { EthereumNetwork } from "./network"

class EthereumStBTC
  // @ts-expect-error TODO: Figure out why type generated by typechain does not
  // satisfy the constraint `Contract`. Error: `Property '[internal]' is missing
  // in type 'StBTC' but required in type 'BaseContract'`.
  extends EthersContractWrapper<StBTCTypechain>
  implements StBTC
{
  constructor(config: EthersContractConfig, network: EthereumNetwork) {
    let artifact: EthersContractDeployment

    switch (network) {
      case "sepolia":
        artifact = stBTC
        break
      case "mainnet":
      default:
        throw new Error("Unsupported network")
    }

    super(config, artifact)
  }

  /**
   * Get a generic chain identifier.
   * @returns Value of the basis for calculating final BTC balance.
   * @see {StBTCTypechain#balanceOf}
   */
  balanceOf(identifier: ChainIdentifier): Promise<bigint> {
    return this.instance.balanceOf(`0x${identifier.identifierHex}`)
  }

  /**
   * Get a generic chain identifier.
   * @returns Maximum withdraw value.
   * @see {StBTCTypechain#assetsBalanceOf}
   */
  assetsBalanceOf(identifier: ChainIdentifier): Promise<bigint> {
    return this.instance.assetsBalanceOf(`0x${identifier.identifierHex}`)
  }
}

// eslint-disable-next-line import/prefer-default-export
export { EthereumStBTC }
