import { BitcoinRawTxVectors, Hex } from "@keep-network/tbtc-v2.ts"
import { TbtcDepositor as TbtcDepositorTypechain } from "core/typechain/contracts/tbtc/TbtcDepositor"
// TODO: How to fix this import?
// eslint-disable-next-line import/no-unresolved
import TbtcDepositor from "core/build/contracts/test/TBTCDepositorStub.sol/TBTCDepositorStub.json"
import { ChainIdentifier, DepositRevealInfo, TBTCDepositor } from "../contracts"
import { EthereumAddress } from "./address"
import { EthersContractConfig, EthersContractWrapper } from "./contract"

/**
 * Ethereum implementation of the TBTCDepositor.
 */
class EthereumTBTCDepositor
  // @ts-expect-error TODO: Figure out why type generated by typechain does not
  // satisfy the constraint `Contract`. Error: `Property '[internal]' is missing
  // in type 'TbtcDepositor' but required in type 'Contract'`.
  extends EthersContractWrapper<TbtcDepositorTypechain>
  implements TBTCDepositor
{
  constructor(config: EthersContractConfig) {
    super(
      config,
      // TODO: get artifact from `core` package.
      {
        abi: TbtcDepositor.abi,
        address: "0x008b3b2f992c0e14edaa6e2c662bec549caa8df1",
        receipt: {
          blockNumber: 1,
        },
      },
    )
  }

  /**
   * @see {TBTCDepositor#getChainIdentifier}
   */
  getChainIdentifier(): ChainIdentifier {
    return this.getAddress()
  }

  /**
   * @see {TBTCDepositor#getTbtcVaultChainIdentifier}
   */
  async getTbtcVaultChainIdentifier(): Promise<ChainIdentifier> {
    const vault = await this.instance.tbtcVault()

    return EthereumAddress.from(vault)
  }

  /**
   * @see {TBTCDepositor#initializeStake}
   */
  async initializeStake(
    bitcoinFundingTransaction: BitcoinRawTxVectors,
    depositReveal: DepositRevealInfo,
    receiver: ChainIdentifier,
    referral: number,
  ): Promise<Hex> {
    const depositTxInfo = {
      version: bitcoinFundingTransaction.version.toPrefixedString(),
      inputVector: bitcoinFundingTransaction.inputs.toPrefixedString(),
      outputVector: bitcoinFundingTransaction.outputs.toPrefixedString(),
      locktime: bitcoinFundingTransaction.locktime.toPrefixedString(),
    }

    const vault = await this.getTbtcVaultChainIdentifier()

    const depositRevealInfo = {
      fundingOutputIndex: depositReveal.fundingOutputIndex,
      blindingFactor: depositReveal.blindingFactor.toPrefixedString(),
      walletPubKeyHash: depositReveal.walletPublicKeyHash.toPrefixedString(),
      refundPubKeyHash: depositReveal.refundPublicKeyHash.toPrefixedString(),
      refundLocktime: depositReveal.refundLocktime.toPrefixedString(),
      vault: `0x${vault.identifierHex}`,
    }

    const tx = await this.instance.initializeStake(
      depositTxInfo,
      depositRevealInfo,
      receiver.identifierHex,
      referral,
    )

    return Hex.from(tx.hash)
  }
}

// eslint-disable-next-line import/prefer-default-export
export { EthereumTBTCDepositor }
