export { default as mysteryBoxImage } from "#/assets/images/benefits/mystery-box.svg"
export { default as rewardsBoostImage } from "#/assets/images/benefits/rewards-boost.svg"
export { default as seasonKeyImage } from "#/assets/images/benefits/season-key.svg"
export { default as rewardsBoostArrowImage } from "#/assets/images/benefits/rewards-boost-arrow.svg"
export { default as bibosBeehiveImage } from "#/assets/images/benefits/bibos-beehive.svg"
