export { default as baseLogo } from "#/assets/images/partner-logos/base-logo.svg"
export { default as thresholdLogo } from "#/assets/images/partner-logos/threshold-logo.svg"
export { default as ledgerLogo } from "#/assets/images/partner-logos/ledger-logo.svg"
export { default as wormholeLogo } from "#/assets/images/partner-logos/wormhole-logo.svg"
export { default as mezoLogo } from "#/assets/images/partner-logos/mezo-logo.svg"
