export { default as okxLogo } from "#/assets/images/partner-logos/okx-logo.svg"
export { default as thresholdLogo } from "#/assets/images/partner-logos/threshold-logo.svg"
export { default as ledgerLogo } from "#/assets/images/partner-logos/ledger-logo.svg"
export { default as xverseLogo } from "#/assets/images/partner-logos/xverse-logo.svg"
export { default as mezoLogo } from "#/assets/images/partner-logos/mezo-logo.svg"
